#!/bin/bash

v="$(_s3d-semver-get | jq -r '.latest')"

if [[ "$v" != $(git log -n 1 --format='%s') ]]; then
  git add -A
  git commit --allow-empty -m "$v"
fi

git tag -s -m release "$v"
git push ssh "$v"
