#!/bin/bash
set -e

# *****************************************************************************
# A script that updates the version the application shows based on the version
# that is in the chanagelog.
# *****************************************************************************

# JQ Raw with SED Escaping the result
get() { _s3d-semver-get | jq -r "$1" | sed 's/\./\\\./g'; }

# Use sed to make a change
change_version() {
  temp_file="s3d-semver-$(uuidgen)"
  sed -e "s/$change_from/$change_to/g" "$1" > "$temp_file"
  mv "$temp_file" "$1"
}

# Get the latest version
latest=$(get .latest)

# Get the branch
branch=$(git branch --show-current)
# Use special logic if this is the main branch
if [[ main == $branch ]]; then
  change_from=$latest
  change_to=$(echo $latest | sed 's/-.*//' )
  change_version 'CHANGELOG.md'
else
  change_to=$latest
  change_from=$(get .penultimate)
fi

if [ -z "$1" ]; then
  exit 0 
fi

# Make the change in the file
change_version "$1"
# Verify that the latest version exists in the file
grep -q -E "$latest" "$1"
