#!/bin/bash
set -e

# Exit if this is the scripts dir
[[ scripts != ${PWD##*/} ]] || exit 0

echo 'FLOW: format'
s3d-format

# If a local init script exists we run it
if [ -f ./s3d-init ]; then
  has_local_init=true
  echo 'FLOW: local init'
  ./s3d-init
fi

# If main.tf exits, we also init by running terrafom validate
if [ -f main.tf ]; then
  echo 'FLOW: tf init'
  log="$HOME/.s3d/logs/$(uuidgen | cut -c 1-8).log"
  { {
    echo 'FLOW: tf get -update'
    terraform get -update

    echo 'FLOW: tf init'
    if [ terraform init ]; then
      echo 'FLOW: tf init - complete'
    else
      echo 'FLOW: WARN tf init failed, will try again in 1 minute'
      sleep 60
      terraform init
      echo 'FLOW: tf init - 2nd try complete'
    fi
  } > $log 2>&1; } || {
    cat $log >&2
    exit -1
  }

  if [ -n "$S3D_TF_LOCK" ]; then
    echo 'FLOW: tf lock update'
    s3d-tf-lock
  fi
fi

# If main.go, we run go tidy
if [ -f main.go ]; then
  echo 'FLOW: go mod tidy'
  go mod tidy
fi

# If a package.json exists, we run npm **UNLESS** a local `s3d-init` script
# exists.
if [ -z $has_local_init ]; then
  if [ -f package.json ]; then
    echo 'FLOW: npm install'
    npm install
  fi
fi
