#!/bin/bash

role=$1
profile=$2

if [ -n "$profile" ]; then
  export AWS_PROFILE="$profile"
  echo -e "AWS_PROFILE=\"$profile\""
fi

# Unset AWS Vars
source s3d-unset-aws-vars

session="$(whoami)"
id="$(aws sts get-caller-identity)"
account="$(echo "$id" | jq -r .Account)"

role=$(
  aws sts assume-role \
  --role-arn "arn:aws:iam::$account:role/$role" \
  --role-session-name "$session" \
  --duration-seconds 43200 \
  | jq -r .Credentials
)

echo "ROLE:"
echo "$role" | jq

export AWS_ACCESS_KEY_ID=$(echo "$role" | jq -r .AccessKeyId)
export AWS_SESSION_TOKEN=$(echo "$role" | jq -r .SessionToken)
export AWS_SECRET_ACCESS_KEY=$(echo "$role" | jq -r .SecretAccessKey)
export AWS_SESSION_TOKEN=$(echo "$role" | jq -r .SessionToken)
