#!/bin/bash

# Exit with error if the origin is not on GitHub
if [ -z "$S3D_GITHUB_USER" ]; then
  echo "ERROR, this only works if you have S3D_GITHUB_USER defined" >&2
  exit 1
fi

if [ -n "$(git remote get-url fork)" ]; then
  echo "INFO: A remote already existed" >&2
  exit 0
fi

# Always add ssh
s3d-git-add-ssh

echo -e "INFO: Adding new fork remote" >&2
git remote add fork "$(git remote get-url ssh \
  | sed 's/.*\:/git@github\.com\:/' \
	| sed "s/s3d-club\//$S3D_GITHUB_USER\/s3d-club--/")"
