#!/bin/bash

# Remove all AWS_ envionment variables with the exception of "AWS_PROFILE" so
# we do not attempt to assume role from an assumed role.
unset $(env | grep -E 'AWS_' | grep -v -E 'PROFILE' | sed 's/=.*//g')

role=$1

session="$(whoami)"
id="$(aws sts get-caller-identity)"
account="$(echo "$id" | jq -r .Account)"

role=$(
  aws sts assume-role \
  --role-arn "arn:aws:iam::$account:role/$role" \
  --role-session-name "$session" \
  | jq -r .Credentials
)

echo "ROLE:"
echo "$role" | jq

export AWS_ACCESS_KEY_ID=$(echo "$role" | jq -r .AccessKeyId)
export AWS_SESSION_TOKEN=$(echo "$role" | jq -r .SessionToken)
export AWS_SECRET_ACCESS_KEY=$(echo "$role" | jq -r .SecretAccessKey)
export AWS_SESSION_TOKEN=$(echo "$role" | jq -r .SessionToken)
