#!/bin/bash
set -e

if [ -e main.tf ]; then
  rm -rf .terraform*

  terraform init

  set +e
  tflock() { terraform providers lock -platform="$1"; }

  tflock linux_amd64
  tflock linux_arm64
else
  echo 'INFO: "main.tf" not found; skipping'
fi
