#!/bin/bash
set -e

# Clean up whitespace
fsed() { 
  sed -i 's/ *$//g' "$1"
  sed -i 's/\t/  /g' "$1"
}

fsed ./*.md

if ls ./s3d-* > /dev/null 2>&1; then
  fsed s3d-*
fi

if [ -f main.go ]; then
  fsed ./*.go
fi

if [ -f main.tf ]; then
  fsed ./*.tf
fi

# Exit if this is the scripts dir
[[ scripts != "${PWD##*/}" ]] || exit 0

# If a local script exists, we run it
if [ -f ./s3d-format ]; then
  ./s3d-format
fi

# If main.tf exits, we also init by running terrafom validate
if [ -f main.tf ]; then
  terraform fmt
fi

# If main.go, we run go fmt
if [ -f main.go ]; then
  go fmt
fi
