#!/bin/bash
# shellcheck disable=SC1091
# shellcheck disable=SC2001
set -e

n=1; p="$1"; message="$p";  [ -n "$p" ] || err="\$$n (message) is required"

[ -z "$err" ] || { {
  echo -e "ERR..: $err"
  echo -e "USE..: $(echo "$0" | sed 's/.*\///') <message>"
  echo -e "ABOUT: Implements a flow for development work"
} >&2; exit 1; }

export S3D_FLOW_FINISHING="$(pwd)"

if [ -e ./s3d-finish ]; then
  ./s3d-finish
  exit
fi

if ! s3d-flow-check; then
  echo -e 'FLOW: check failed'
fi

v=$(s3d-flow-json | jq -r .latest)
v2=$(s3d-flow-json | jq -r .release)
if [[ "$v" == "$v2" ]]; then
  echo "FLOW: ALREADY FINISHED $S3D_MODULE?ref=$(git describe --tags)"
else
  v_=$(echo "$v" | sed 's/\./\\\./')
  v2_=$(echo "$v2" | sed 's/\./\\\./')
  sed -i -e 's/\['"$v_"'\]/\['"$v2_"'\]/' CHANGES.md
  . s3d-flow "$message"
fi

echo "FLOW: FINISHED $S3D_MODULE?ref=$(git describe --tags)"
