#!/bin/bash
# shellcheck disable=SC2001
set -e

latest=$(s3d-flow-json | jq -r .latest)
if [[ $latest != $(echo -n "$latest" | sed 's/-.*//') ]]; then
  echo "FLOW: $latest already started"
  exit 0
fi

v="$latest"
v_major=$(echo "$v" | tr '.' '\n' | head -n 1)
v_minor=$(echo "$v" | tr '.' '\n' | head -n 2 | tail -n 1)
v_minor=$(( v_minor + 1))

item="${1:-**TODO** Planned item}"
{
  echo ""
  echo "## $v_major.$v_minor.0-1"
  echo "- $item"
} >> CHANGES.md
