#!/bin/bash
set -e

s3d-git-add-fork

git tag -d $(git tag)
git fetch fork --tags
git tag \
| sed 's/^/git push fork :/' \
| sh

git tag -d $(git tag)
git fetch ssh --tags
git tag | grep -v v | sed 's/^/s3d-flow-tag-rm /' | sh
git push fork --tags

s3d-git-list-version-tags
