#!/bin/bash
# shellcheck disable=SC2001
set -e

# Get the flow message
if [ -z "$S3D_FLOW_MSG" ]; then
  S3D_FLOW_MSG="${1:-Changed}"
fi

# Get versions so we can find the block of lines in `CHANGES.md`
v=$(s3d-flow-json | jq -r '.latest')
v_=$(echo "$v" | sed 's/\./\\\./')

# Get the block of lines from `CHANGES.md`
block=$(sed -e '/## \[[a-z]/,$d' < CHANGES.md | sed -n -e "/$v_/,\$p")
block=$(echo "$block" | grep -v -E '^##')

# Determine how much is done.
done=$(echo "$block"  | grep -E '^-' | grep -c -v -E '^- \*\*TODO\*\*' || true)
items=$(echo "$block" | grep -c -E '^-' || true)

# Construct the commit message subject line
if [[ $done == "$items" ]]; then
	commit=$"$v $S3D_FLOW_MSG"
else
	commit=$"$v $S3D_FLOW_MSG; $done of $items completed"
fi

# Create the full commit message
commit="$commit"$'\n\n';
commit="$commit$block"

# Issue the commit
git add -A
git commit -m "$commit"
