#!/bin/bash
set -e

# First make certain that all tags have been pushed to the fork
git push --no-verify fork --tags --quiet

# Remove anything that looks like a pre-release tag
git tag \
| grep -E '^[0-9]+\.[0-9]+\.[0-9]+-.*$' \
| sed 's/^/s3d-flow-tag-rm /' \
| sh
