#!/bin/bash
set -e

s3d-flow "$1" 03-acm
s3d-flow "$1" 03-az-vm
s3d-flow "$1" 03-ecr
s3d-flow "$1" 03-eg-open
s3d-flow "$1" 03-ig-open
s3d-flow "$1" 03-ssh
s3d-flow "$1" 04-ec2
s3d-flow "$1" 04-eks
s3d-flow "$1" 04-waf
s3d-flow "$1" 05-site
s3d-flow "$1" 05-site-group
